<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.6</version>
		<relativePath/>
	</parent>
	<groupId>uk.gov.companieshouse</groupId>
	<artifactId>strike-off-partner-objections-api</artifactId>
	<version>unversioned</version>
	<properties>
		<java.version>21</java.version>
        <structured-logging.version>3.0.57</structured-logging.version>

		<!-- Override vulnerable Tomcat version -->
		<tomcat.version>11.0.22</tomcat.version>
		<private-api-sdk-java.version>6.0.19</private-api-sdk-java.version>

        <!-- Sonar Plugin and Configuration -->
        <sonar-maven-plugin.version>4.0.0.4121</sonar-maven-plugin.version>
        <sonar.token>${CODE_ANALYSIS_TOKEN}</sonar.token>
        <sonar.host.url>${CODE_ANALYSIS_HOST_URL}</sonar.host.url>
        <sonar.tests>test</sonar.tests>
        <sonar.test.inclusions>**/test/**/**.test.*</sonar.test.inclusions>
        <sonar.projectName>strike-off-partner-objections-api</sonar.projectName>
        <sonar.projectKey>uk.gov.companieshouse:strike-off-partner-objections-api</sonar.projectKey>
        <sonar.java.binaries>${project.basedir}/target,${project.basedir}/target/*</sonar.java.binaries>
        <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/target/site/jacoco/jacoco.xml,
            ${project.basedir}/target/site/jacoco-it/jacoco.xml
        </sonar.coverage.jacoco.xmlReportPaths>
        <sonar.jacoco.reports>${project.basedir}/target/site</sonar.jacoco.reports>
        <sonar.java.binaries>${project.basedir}/target</sonar.java.binaries>
		<sonar.exclusions>**/models/**</sonar.exclusions>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc-test</artifactId>
			<scope>test</scope>
		</dependency>
        <dependency>
            <groupId>uk.gov.companieshouse</groupId>
            <artifactId>structured-logging</artifactId>
            <version>${structured-logging.version}</version>
        </dependency>
		<dependency>
			<groupId>uk.gov.companieshouse</groupId>
			<artifactId>private-api-sdk-java</artifactId>
			<version>${private-api-sdk-java.version}</version>
		</dependency>
	</dependencies>

    <profiles>
        <profile>
            <id>sonar-pr-analysis</id>
            <properties>
                <sonar.pullrequest.branch>${CODE_ANALYSIS_PULL_REQUEST_BRANCH}</sonar.pullrequest.branch>
                <sonar.pullrequest.key>${CODE_ANALYSIS_PULL_REQUEST_KEY}</sonar.pullrequest.key>
                <sonar.pullrequest.base>${CODE_ANALYSIS_PULL_REQUEST_BASE}</sonar.pullrequest.base>
                <sonar.pullrequest.github.repository>${CODE_ANALYSIS_PULL_REQUEST_REPO}</sonar.pullrequest.github.repository>
            </properties>
        </profile>
    </profiles>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>${sonar-maven-plugin.version}</version>
			</plugin>
		</plugins>
	</build>

</project>
